
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/proj-rec-s25-15
owner: ucsb-cs156-s25
repo_name: proj-rec-s25-15
pull_requests: [{"author":{"id":"U_kgDOCVG6FA","is_bot":false,"login":"BryceInouye","name":""},"headRefName":"bi-rec-placeholder-pages","number":44,"title":"Bi - Add placeholder pages for Index, Edit, Create for request types (WIP)","url":"https://github.com/ucsb-cs156-s25/proj-rec-s25-15/pull/44"},{"author":{"id":"U_kgDOCM79zg","is_bot":false,"login":"Tyler-W0ng","name":""},"headRefName":"tw-RequestsTab-Admin","number":43,"title":"Tw requests tab admin","url":"https://github.com/ucsb-cs156-s25/proj-rec-s25-15/pull/43"},{"author":{"id":"U_kgDOCVG6FA","is_bot":false,"login":"BryceInouye","name":""},"headRefName":"bi-rec-table-component","number":42,"title":"bi - Add request type table component with tests","url":"https://github.com/ucsb-cs156-s25/proj-rec-s25-15/pull/42"},{"author":{"id":"U_kgDOCVG6FA","is_bot":false,"login":"BryceInouye","name":""},"headRefName":"bi-eslint-directory-fix","number":35,"title":"bi - Modify package.json so it ignores build directory","url":"https://github.com/ucsb-cs156-s25/proj-rec-s25-15/pull/35"},{"author":{"id":"U_kgDOCVG6FA","is_bot":false,"login":"BryceInouye","name":""},"headRefName":"bi-rec-form-component","number":33,"title":"bi - Add request type form component with tests","url":"https://github.com/ucsb-cs156-s25/proj-rec-s25-15/pull/33"}]
