
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/proj-rec-s25-15
owner: ucsb-cs156-s25
repo_name: proj-rec-s25-15
pull_requests: [{"author":{"id":"U_kgDOCJYDtQ","is_bot":false,"login":"Esomevath","name":"Lucas Havemose"},"headRefName":"lh-add-hardcoded-request-types","number":60,"title":"Add RequestTypes on startup","url":"https://github.com/ucsb-cs156-s25/proj-rec-s25-15/pull/60"},{"author":{"id":"U_kgDOB9EidQ","is_bot":false,"login":"davidduena","name":""},"headRefName":"dd-remove-studentrole","number":58,"title":"Dd- remove studentrole","url":"https://github.com/ucsb-cs156-s25/proj-rec-s25-15/pull/58"},{"author":{"id":"U_kgDOCJYDtQ","is_bot":false,"login":"Esomevath","name":"Lucas Havemose"},"headRefName":"lh-recommendation-type-foreign-key","number":51,"title":"Modified RecommendationRequest recommendationType to be a foreign key to RequestType","url":"https://github.com/ucsb-cs156-s25/proj-rec-s25-15/pull/51"}]
