
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/proj-rec-s25-15
owner: ucsb-cs156-s25
repo_name: proj-rec-s25-15
pull_requests: [{"author":{"id":"U_kgDOCJYDtQ","is_bot":false,"login":"Esomevath","name":"Lucas Havemose"},"headRefName":"lh-add-hardcoded-request-types","number":60,"title":"Add RequestTypes on startup","url":"https://github.com/ucsb-cs156-s25/proj-rec-s25-15/pull/60"},{"author":{"id":"U_kgDOCVHkAA","is_bot":false,"login":"yuecao365","name":""},"headRefName":"yc-addTooltips","number":59,"title":"Yc add tooltips","url":"https://github.com/ucsb-cs156-s25/proj-rec-s25-15/pull/59"},{"author":{"id":"U_kgDOB9EidQ","is_bot":false,"login":"davidduena","name":""},"headRefName":"dd-remove-studentrole","number":58,"title":"Dd- remove studentrole","url":"https://github.com/ucsb-cs156-s25/proj-rec-s25-15/pull/58"},{"author":{"id":"U_kgDOB9EidQ","is_bot":false,"login":"davidduena","name":""},"headRefName":"dd-remove-backend-student","number":57,"title":"Dd -remove backend student","url":"https://github.com/ucsb-cs156-s25/proj-rec-s25-15/pull/57"},{"author":{"id":"U_kgDOB9EidQ","is_bot":false,"login":"davidduena","name":""},"headRefName":"dd-remove-frontend-student","number":56,"title":"Dd -remove frontend student","url":"https://github.com/ucsb-cs156-s25/proj-rec-s25-15/pull/56"},{"author":{"id":"U_kgDOB9EidQ","is_bot":false,"login":"davidduena","name":""},"headRefName":"davidduena-proj-rec-defaultstudent","number":55,"title":"dd- proj rec defaultstudent","url":"https://github.com/ucsb-cs156-s25/proj-rec-s25-15/pull/55"},{"author":{"id":"MDQ6VXNlcjg1MDA2ODI4","is_bot":false,"login":"perryjirakit","name":""},"headRefName":"pt-pending-page","number":54,"title":"page for pending request for storybook and main web","url":"https://github.com/ucsb-cs156-s25/proj-rec-s25-15/pull/54"},{"author":{"id":"U_kgDOCJYDtQ","is_bot":false,"login":"Esomevath","name":"Lucas Havemose"},"headRefName":"lh-recommendation-type-foreign-key","number":51,"title":"Modified RecommendationRequest recommendationType to be a foreign key to RequestType","url":"https://github.com/ucsb-cs156-s25/proj-rec-s25-15/pull/51"},{"author":{"id":"U_kgDOCVHkAA","is_bot":false,"login":"yuecao365","name":""},"headRefName":"yc-StudentProfile-pages","number":49,"title":"Yc student profile pages","url":"https://github.com/ucsb-cs156-s25/proj-rec-s25-15/pull/49"}]
